[www]
listen = 127.0.0.1:9000
listen.owner = www-data
listen.group = www-data

user = www-data
group = www-data

pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 10
pm.max_requests = 1000

; Timeouts
request_terminate_timeout = 300

; Logs
access.log = /var/log/php-fpm/access.log
catch_workers_output = yes

; Environment
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
